FROM node:18.20

# actualizar npm global
RUN npm install -g npm@latest

# copiar start.sh para el contenedor
COPY .docker/start.sh /usr/local/bin/start.sh

# asignar permisos de ejecución al script
RUN chmod +x /usr/local/bin/start.sh

WORKDIR /app

# copiar package.json y package-lock.json
COPY package*.json ./

EXPOSE 3000

CMD ["/usr/local/bin/start.sh"]
